### ISSUE TITLE
Botão Pós-prandial obrigatório em Atendimento/Glicemia

### ISSUE THREAD

**Issue by tiagolii** [williamborba/drugstore-system#36]
Se é um botão, não deveria ser obrigatório para se poder salvar um novo serviço.

**Comment by tiagolii** [comment]
| Campo | Imagem |
| --- | --- |
| Botão `Pós-prandial` | ![bug atendimento glicemia botao](https://cloud.githubusercontent.com/assets/22398687/21154153/71694230-c154-11e6-8866-546250b74c09.png) |

**Comment by williamborba** [comment]
:+1:
