### ISSUE TITLE
Campo "Horas em jejum" não aceita valor "0"

### ISSUE THREAD

**Issue by tiagolii** [williamborba/drugstore-system#38]

**Comment by tiagolii** [comment]
| Campo | Imagem |
| --- | --- |
| Campo `Horas de jejum` | ![atendimento glicemia bug jejum](https://cloud.githubusercontent.com/assets/22398687/21272283/aa77305c-c3a5-11e6-8c7d-057950cc05dd.png) |

**Comment by williamborba** [comment]
ok
